language: node_js
node_js:
  - "5.6.0"

branches:
  only:
    - master

env:
    - TEST: $TEST
    
script:
script:
  - if [ "$TRAVIS_BRANCH" = "develop" ]; then process.env.TEST=$develop; fi
  - node env.js
