language: node_js
node_js:
  - "5.6.0"

branches:
  only:
    - master
    - develop

env:
  global:
    - ENV= get_env_specific_value.sh
    - DEV: $DEVELOP
    - PROD: $PROD
    - TEST1= $($ENV $DEV $PROD)
    
script:
script:
  - node env.js
